name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./pet-data-management/pom.xml
          mvn clean package -f ./product-purchase/pom.xml
          mvn clean package -f ./social-media-interaction/pom.xml
          mvn clean package -f ./product-review/pom.xml
          mvn clean package -f ./product/pom.xml

      - name: Docker Build and push for PetDataManagement
        uses: docker/build-push-action@v4
        with:
          context: ./pet-data-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/pet-data-management:latest
            ghcr.io/${{ github.repository }}/pet-data-management:${{ github.ref_name }}
            
      - name: Docker Build and push for ProductPurchase
        uses: docker/build-push-action@v4
        with:
          context: ./product-purchase
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/product-purchase:latest
            ghcr.io/${{ github.repository }}/product-purchase:${{ github.ref_name }}
            
      - name: Docker Build and push for SocialMediaInteraction
        uses: docker/build-push-action@v4
        with:
          context: ./social-media-interaction
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/social-media-interaction:latest
            ghcr.io/${{ github.repository }}/social-media-interaction:${{ github.ref_name }}
            
      - name: Docker Build and push for ProductReview
        uses: docker/build-push-action@v4
        with:
          context: ./product-review
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/product-review:latest
            ghcr.io/${{ github.repository }}/product-review:${{ github.ref_name }}
            
      - name: Docker Build and push for Product
        uses: docker/build-push-action@v4
        with:
          context: ./product
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/product:latest
            ghcr.io/${{ github.repository }}/product:${{ github.ref_name }}
            
