server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: pet-data-management
          uri: http://localhost:8082
          predicates:
            - Path=/petProfiles/**, /recommendedProducts/**, /productProfiles/**, 
        - id: product-purchase
          uri: http://localhost:8083
          predicates:
            - Path=/purchasedProducts/**, 
        - id: social-media-interaction
          uri: http://localhost:8084
          predicates:
            - Path=/socialMediaPosts/**, 
        - id: product-review
          uri: http://localhost:8085
          predicates:
            - Path=/productReviews/**, 
        - id: product
          uri: http://localhost:8086
          predicates:
            - Path=/products/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: pet-data-management
          uri: http://petDataManagement:8080
          predicates:
            - Path=/petProfiles/**, /recommendedProducts/**, /productProfiles/**, 
        - id: product-purchase
          uri: http://productPurchase:8080
          predicates:
            - Path=/purchasedProducts/**, 
        - id: social-media-interaction
          uri: http://socialMediaInteraction:8080
          predicates:
            - Path=/socialMediaPosts/**, 
        - id: product-review
          uri: http://productReview:8080
          predicates:
            - Path=/productReviews/**, 
        - id: product
          uri: http://product:8080
          predicates:
            - Path=/products/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
